org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1024m -Dkotlin.daemon.jvm.options=-Xmx4g
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true

android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=true

reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
newArchEnabled=true
hermesEnabled=true

expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false
EX_DEV_CLIENT_NETWORK_INSPECTOR=true
expo.useLegacyPackaging=false
expo.edgeToEdgeEnabled=true

android.minSdkVersion=24
android.compileSdkVersion=35
android.targetSdkVersion=35
android.buildToolsVersion=35.0.0
android.kotlinVersion=2.0.21
