import { Dimensions, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#c5def3ff",
    padding: 20,
    gap: 16,
  },
  input: {
    borderWidth: 5,
    borderRadius: 12,
    padding: 5,
    marginBottom: 20,
    fontSize: 16,
    borderColor: "#9ddff3ff",
    backgroundColor: "#ffffffff",
    color: "#000000ff",
    
  },
label: {
  fontSize: 17,
  fontWeight: "600",
  marginBottom: 8,
  color: "#14265c",
  textAlign: "center", // <-- dodane wyrównanie do środka
},

  counterContainer: {
    marginBottom: 20,
  },
  counterButtons: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#14265c",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginTop: 8,
  },
  counterButton: {
    backgroundColor: "#00C1F3",
    borderRadius: 8,
    padding: 10,
  },
  counterText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  counterValue: {
    fontSize: 18,
    fontWeight: "600",
    color: "#E1F1FF",
  },
  switchContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  switchLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  iconRow: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 8,
    gap: 12,
  },
  submitButton: {
    backgroundColor: "#00C1F3",
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: "center",
    shadowColor: "#00E6FB",
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 5,
  },
  submitButtonText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "bold",
  },
  placeTileContainer: {
    width: "100%",
    alignItems: "center",
    marginBottom: 16,
  },
  placeTile: {
    backgroundColor: "#1c3c6b",
    padding: 16,
    borderRadius: 12,
    width: Dimensions.get("window").width - 70,
    alignSelf: "center",
    shadowColor: "#00E6FB",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  placeText: {
    fontSize: 17,
    fontWeight: "600",
    color: "#B0DFFF",
    textAlign: "center",
  },
  placeAddress: {
    fontSize: 13,
    color: "#CFCFCF",
    textAlign: "center",
    marginTop: 6,
  },
  iconRowBottom: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 8,
    gap: 10,
  },
  iconButton: {
    backgroundColor: "#00C1F3",
    padding: 8,
    borderRadius: 8,
  },
  dateRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 16,
  },
  datePickerBox: {
    flex: 1,
    borderWidth: 5,
    borderColor: "#00C1F3",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#14265c",
  },
  datePickerLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#B0DFFF",
    marginBottom: 4,
  },
  datePickerText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#E1F1FF",
  },
});
